security:
    encoders:
        App\Entity\Prof:
            algorithm: auto
        App\Entity\Eleve:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto
        App\Entity\User:
            algorithm: auto




    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
                # manager_name: user
        prof_provider:
            entity:
                class: App\Entity\Prof
                property: email
                # manager_name: user
        eleve_provider:
            entity:
                class: App\Entity\Eleve
                property: email
                # manager_name: eleve
        chain_provider:
            chain:
                providers: ['prof_provider', 'eleve_provider']
        # used to reload user from session & other features (e.g. switch_user)
        # chain_provider:
        #     chain:
        #         providers: [in_memory, user_db]
        # in_memory:
        #     memory:
        #         users:
        #             foo: { password: test }
        # user_db:
        #     entity: { class: App\Entity\Prof, property: email }
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false   
        eleve_security:
            pattern: ^/eleve/
            provider: eleve_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\EleveAuthenticator
            # user_checker: App\Security\UserChecker
            logout:
                path: logout_eleve
                # invalidate_session: true

                # target: login_eleve
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path:     /
        prof_security:
            pattern: ^/prof/
            provider: prof_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\ProfAuthenticator
            # user_checker: App\Security\UserChecker
            logout:
                path: logout_prof
                # invalidate_session: true

                # target: login_prof
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path:     /
        admin_security:
            pattern: ^/admin/
            provider: admin_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
            logout:
                path: logout_admin
                # where to redirect after logout
            # target: apzp_any_route
        default:
            pattern: ^/
            anonymous: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/eleve, roles: ROLE_ELEVE }
    #     - { path: ^/prof, roles: ROLE_PROF }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROF, ROLE_ELEVE]
        ROLE_ELEVE:       ROLE_USER
        ROLE_PROF:       ROLE_USER

