security:
    encoders:
        App\Entity\Prof:
            algorithm: auto
        App\Entity\Eleve:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto
        App\Entity\User:
            algorithm: auto

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

        prof_provider:
            entity:
                class: App\Entity\Prof
                property: email

        eleve_provider:
            entity:
                class: App\Entity\Eleve
                property: email

        chain_provider:
            chain:
                providers: ['prof_provider', 'eleve_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false   

        eleve_security:
            pattern: ^/eleve/
            provider: eleve_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\EleveAuthenticator

            logout:
                path: logout_eleve

        prof_security:
            pattern: ^/prof/
            provider: prof_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\ProfAuthenticator

            logout:
                path: logout_prof

        admin_security:
            pattern: ^/admin/
            provider: admin_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
            logout:
                path: logout_admin

        default:
            pattern: ^/
            anonymous: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ELEVE:       ROLE_USER
        ROLE_PROF:       ROLE_USER

