# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    transport:        smtp
    username:         arnaud.straumann@free.fr
    password:         Szolnok67
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    # spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
